version: '3.8'

services:
  app:
    build: .
    container_name: backend
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      - DB_URL=jdbc:postgresql://postgresdb:5432/auctiondb
      - REDIS_URL=${REDIS_URL}
    depends_on:
      - postgresdb

  postgresdb:
    image: postgres:15-alpine
    container_name: postgres_auction
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=auctiondb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
